services:
  web:
    image: httpd:latest
    container_name: gestor-de-tempo
    ports:
      - "8080:80"
    volumes:
      - ./website:/usr/local/apache2/htdocs
    restart: unless-stopped # o container reinicia se o Docker reiniciar
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
